trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'dicePipeline'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform --version
          terraform init
          terraform plan
        addSpnToEnvironment: true