trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@1
  displayName: terraform init
  inputs:
    command: init

- task: TerraformCLI@1
  displayName: terraform plan -out=tfplan
  inputs:
    runAzLogin: true
    command: 'plan'
    environmentServiceNameAzureRM: '$(subscription)'
