trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'dicePipeline'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Azure CLI login using Service Principal"
      az account set --subscription $(azureSubscription)
      terraform init
    failOnStandardError: true
# - task: TerraformCLI@1
#   displayName: terraform init
#   inputs:
#     command: init
#     azureSubscription: dicePipeline
#     runAzLogin: true
#     environmentServiceName: dicePipeline
#     allowTelemetryCollection: true

- task: TerraformCLI@1
  displayName: terraform plan -out=tfplan
  inputs:
    command: plan
    azureSubscription: dicePipeline
    environmentServiceName: dicePipeline
    runAzLogin: true
    allowTelemetryCollection: true
