trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: AzureCLI@2
  displayName: "Terraform"
  inputs:
    azureSubscription:  dicePipeline
    scriptType: bash
    addSpnToEnvironment: true
    scriptLocation: inlineScript
    inlineScript: |
      export ARM_CLIENT_ID=6ae75f68-d956-4829-a902-1e86d1998201
      export ARM_CLIENT_SECRET=vei8Q~tStpzTRKzDr2sPpAFUciprZJjWtvmvha_I
      export ARM_TENANT_ID=8e2dc2c8-cb38-4b25-91cf-cca92778bd6a

      terraform init
# - task: TerraformCLI@1
#   displayName: terraform init
#   inputs:
#     command: init
#     azureSubscription: dicePipeline
#     runAzLogin: true
#     environmentServiceName: dicePipeline
#     allowTelemetryCollection: true

- task: TerraformCLI@1
  displayName: terraform plan -out=tfplan
  inputs:
    command: plan
    azureSubscription: dicePipeline
    environmentServiceName: dicePipeline
    runAzLogin: true
    allowTelemetryCollection: true
