trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@1
  displayName: terraform init
  inputs:
    command: init
    providerAzureRmSubscriptionId: 'e4cf2944-5342-4787-b990-418828e39bfc'
    runAzLogin: true
    allowTelemetryCollection: true

- task: Bash@3
  inputs:
    azureSubscription: 'dicePipeline'
    targetType: 'inline'
    script: 'az login'
- task: TerraformCLI@1
  displayName: terraform plan -out=tfplan
  inputs:
    azureSubscription: 'dicePipeline'
    command: 'plan'
    environmentServiceName: 'dicePipeline'
    runAzLogin: true
    allowTelemetryCollection: true
