trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Terraform version to use
  terraformVersion: '1.0.0'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- task: UseTerraform@0
  inputs:
    version: $(terraformVersion)

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
