trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: Visual Studio Enterprise(17b12858-3960-4e6f-a663-a06fdae23428)
  # resourceGroup: resourcegroup-tfstate
  # storageAccount: terraformtfstateskip
  # container: tfstate
  # tfstateFile: terraform.tfstate
  # anyTfChanges: false

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    # backendServiceArm: '$(subscription)'
    # backendAzureRmResourceGroupName: '$(resourceGroup)'
    # backendAzureRmStorageAccountName: '$(storageAccount)'
    # backendAzureRmContainerName: '$(container)'
    # backendAzureRmKey: '$(tfstateFile)'

- task: TerraformCLI
  displayName: terraform plan -out=tfplan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/'
    # commandOptions: '-out=tfplan'
    # commandOptions: '-detailed-exitcode -out=tfplan'
    environmentServiceNameAzureRM: '$(subscription)'

# - task: TerraformCLI
#   displayName: terraform apply tfplan
#   condition: eq(variables.anyTfChanges, true)
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/'
#     commandOptions: 'tfplan'
#     environmentServiceNameAzureRM: '$(subscription)'