trigger:
# - main
- none

variables:
  azureSubscription: 'dicePipeline'
  containerRegistry: 'dockerSC'

jobs:
- job: Checkout
  displayName: 'Checkout Code INITIAL INFRA'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - checkout: self

- job: Terraform
  displayName: 'Deploy Terraform Infrastructure'
  # dependsOn: BuildAndDeploy
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: terraformTasks.yaml
    parameters:
      workingDirectory: 'initialInfra'

