trigger:
- main
# - none

variables:
  azureSubscription: 'dicePipeline'
  containerRegistry: 'dockerSC'
  imageTag: 'latest'
  dockerfilePath: '$(Build.SourcesDirectory)/repo/Dockerfile'
  gitRepoUrl: 'https://github.com/UttU28/Dice-JobScraping.git'
  gitBranch: 'main'

jobs:
- job: Checkout
  displayName: 'Checkout Code JOBSCRAPING'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - checkout: self

# - job: BuildAndDeploying
#   displayName: 'Build and Deploy'
#   dependsOn: Checkout
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - task: AzureKeyVault@2
#     displayName: 'Get Secrets from Key Vault'
#     inputs:
#       azureSubscription: '$(azureSubscription)'
#       KeyVaultName: 'thisdicekeyvault'
#       SecretsFilter: '*'
#   - template: buildAndDeploy.yaml
#     parameters:
#       containerRegistry: '$(containerRegistry)'
#       acrName: '$(acrName)'
#       imageName: '$(jobscraping-name)'
#       imageTag: '$(imageTag)'
#       dockerfilePath: '$(dockerfilePath)'
#       artifactName: '$(jobscraping-name)_ARTIFACT'
#       imageRepository: '$(acrName).azurecr.io/$(jobscraping-name)'
#       gitRepoUrl: '$(gitRepoUrl)'
#       gitBranch: '$(gitBranch)'

- job: Terraform
  displayName: 'Deploy Terraform Infrastructure'
  dependsOn: Checkout
  # dependsOn: BuildAndDeploying
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: terraformTasks.yaml
    parameters:
      workingDirectory: 'dataScraping'
