trigger:
- main

variables:
  azureSubscription: 'dicePipeline'
  containerRegistry: 'dockerSC'
  acrName: 'thisacr'
  imageName: 'dicewebview'
  imageTag: 'latest'
  imageRepository: '$(acrName).azurecr.io/$(imageName)'
  artifactName: '$(imageName)_ARTIFACT'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  gitRepoUrl: 'https://github.com/UttU28/Dice-WebView.git'
  gitBranch: 'main'

jobs:
- job: CheckoutCode
  displayName: 'Checkout Code'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self  # This is the correct syntax for checking out the current repository

- job: GetSecrets
  displayName: 'Get Secrets from Key Vault'
  dependsOn: CheckoutCode
  steps:
  - task: AzureKeyVault@2
    displayName: 'Get Secrets from Key Vault'
    inputs:
      azureSubscription: '$(azureSubscription)'
      KeyVaultName: 'thisdicekeyvault'
      SecretsFilter: '*'
      RunAsPreJob: true

- template: buildAndDeploy.yaml
  parameters:
    containerRegistry: '$(containerRegistry)'
    acrName: '$(acrName)'
    imageName: '$(imageName)'
    imageTag: '$(imageTag)'
    dockerfilePath: '$(dockerfilePath)'
    artifactName: '$(artifactName)'
    imageRepository: '$(imageRepository)'
    gitRepoUrl: '$(gitRepoUrl)'
    gitBranch: '$(gitBranch)'

- job: TerraformTask
  displayName: 'Deploy Terraform Infra'
  dependsOn: CheckoutCode
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: terraformTasks.yaml
    parameters:
      workingDirectory: 'webApp'
