trigger:
- main

variables:
  azureSubscription: 'dicePipeline'
  containerRegistry: 'dockerSC'
  acrName: 'thisacr'
  imageName: 'dicewebview'
  imageTag: 'latest'
  imageRepository: '$(acrName).azurecr.io/$(imageName)'
  artifactName: '$(imageName)_ARTIFACT'
  dockerfilePath: '$(Build.SourcesDirectory)/repo/Dockerfile'
  gitRepoUrl: 'https://github.com/UttU28/Dice-WebView.git'
  gitBranch: 'main'
  webappName: 'dicesaralapply'
  rgName: 'this-dice-jobscraping-rg'
  githubRepository: 'UttU28/updateSites'
  githubEventType: 'update_index_html'
  containerAppUrl: '$(CONTAINER_APP_URL)'  # Assuming this variable is set elsewhere in your pipeline

jobs:
- job: Checkout
  displayName: 'Checkout Code'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - checkout: self

- job: ExtractTerraformOutput
  displayName: 'Extract Terraform Output'
  dependsOn: Checkout
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    displayName: 'Extract Container App URL'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: bash
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: |
        CONTAINER_APP_URL=$(az containerapp show \
          --resource-group $(rgName) \
          --name $(webappName) \
          --query "properties.configuration.ingress.fqdn" \
          --output tsv)
        echo "##vso[task.setvariable variable=CONTAINER_APP_URL]$CONTAINER_APP_URL"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r $(Build.SourcesDirectory)/requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python $(Build.SourcesDirectory)/test.py $(pat_token)
    displayName: 'Trigger the Workflow'
    env:
      pat_token: $(pat_token)


# Uncomment if Key Vault integration is required
# - job: GetSecrets
#   displayName: 'Get Secrets from Key Vault'
#   dependsOn: Checkout
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - task: AzureKeyVault@2
#     displayName: 'Get Secrets from Key Vault'
#     inputs:
#       azureSubscription: '$(azureSubscription)'
#       KeyVaultName: 'thisdicekeyvault'
#       SecretsFilter: '*'
#       RunAsPreJob: true

# Uncomment if Build and Deploy tasks are needed
# - job: BuildAndDeploy
#   displayName: 'Build and Deploy'
#   dependsOn: GetSecrets
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - template: buildAndDeploy.yaml
#     parameters:
#       containerRegistry: '$(containerRegistry)'
#       acrName: '$(acrName)'
#       imageName: '$(imageName)'
#       imageTag: '$(imageTag)'
#       dockerfilePath: '$(dockerfilePath)'
#       artifactName: '$(artifactName)'
#       imageRepository: '$(imageRepository)'
#       gitRepoUrl: '$(gitRepoUrl)'
#       gitBranch: '$(gitBranch)'

# Uncomment if Terraform deployment is required
# - job: Terraform
#   displayName: 'Deploy Terraform Infrastructure'
#   dependsOn: BuildAndDeploy
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - template: terraformTasks.yaml
#     parameters:
#       workingDirectory: 'webApp'

